version: '3.4'
services:
  ssv.avado.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.3.4
    image: 'ssv.avado.dappnode.eth:0.0.4'
    restart: always
    volumes:
      - 'ssv:/data'
    ports:
      - '13001:13001'
      - '12001:12001/udp'
volumes:
  ssv: {}
