version: '3.4'
services:
  ssv.avado.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.2.3
    image: 'ssv.avado.dappnode.eth:0.0.10'
    restart: always
    volumes:
      - 'ssv:/data'
    ports:
      - '13001:13001'
      - '12001:12001/udp'
      - '9999:9999'
    environment:
      - BEACONNODEADDR=http://teku.my.ava.do:5051
      - EXECUTIONCLIENTADDR=ws://ethchain-geth.my.ava.do:8546
      - NETWORK=mainnet
volumes:
  ssv: {}
